T was not different than any other college student you would see on the street, he had the dream that almost any normal person had, getting a well paying job and spending it on whatever made him happy. He had the same routine everyday, waking up, going to college, coming back home and spending time with his friends at home, either playing a sport or simply chatting away with them while walking around the block. Back at college he was part of a big friend group who he always talked to and laughed with. He wished the best for everyone around him, helped people when they needed it, never once judging anybody for something they couldnt control. On the surface you would expect him to be leading a life anybody would desire. He had good grades, was sharper than most of his peers, and almost anything materialistic he could want. He didn't drink like most of his peers. 

However ideal this seemed to be on paper, the reality was totally different. He didn't think he truly belonged anywhere. Although he was as nice to people as he could be, never making fun of anybody's insecurities, always treating them with affection, he didn't go one day without being the butt of a nasty joke or a backhanded comment. He had grown to not care about most of these, but some of them really hurt his feelings. He would never show these or open up to anyone about it, but deep down he was tired of being treated this was for no reason. Cruel jokes about the way he looked, or how outdated his fashion sense was hurt him the most because it was something he could not control. Such experiences had rendered him unable to compliment others in any way. Anytime he felt a shimmer of confidence in him, it was immediately shot down by hurtful words even if they were intended as jokes. He had begun to feel afraid of staying in a group as he didnt want to catch a stray his way that would ruin his mood. He could not perceive how anyone could be this heartless let alone all his close friends and family. He was never alone but still always was lonely.

At college when he had events such as etnic days, he would leave home feeling happy about the new 'kurta' he was wearing, only for it to be called something old people would wear at park. This might have got a few laughs out of his group but the effect it had on him was long lasting. His picture on ID cards was a topic of repetetive mocking, how it looked like a forty year old IT man trying to sign in to work. He was regularly spoken over. He was regularly upset. Every morning on his way to college, he was often met with critisism on matters he was most insecure of. He could not catch a break. He could not make it stop. 

T was not always nice before. When he was younger he was one of the people he had come to dispise. He was relentless in insulting people's intelligence or bullying people younger than him, something he would do to project what was happenning to him. T was always above average at the sports he played, and often played with people a lot older to him thereby becoming an easy target to be mocked. However, when he reached an age where he could tell right and wrong apprt, he had morphed into his current self. He had started avoiding college events of which dressing up was a part to avoid having his day ruined by somebody trying to get a laugh out of his group. Nothing he did seemed to make him happy. All roads led to the same destination. All actions led to the same result. There was no one he could talk to about the way he was feeling without being accused of playing the victim card. 

T would try to deal with it by laying in his bed staring at his ceiling wondering if this is all a consequence, a penance for his actions when he was younger. This only made him recall everyway he has wronged a person before, only worsening his pain. He would try to be a people-pleaser. He would tell himself "Don't take critisism from someone whose advice you would not take", but actually no taking words to his heart felt impossible. He would try to look at inspirational youtube videos on how to deal with his problems or read deep motivational quotes off of pintrest. None of this seemed to be of any resolve. This was not a fight he could win. This was how he would have to live his life.




